# Introduction to Scikit-learn

#### Content
- An end-to-end Scikit-Learn workflow
- Getting the data ready
- Choose the right estimator/algorithm for our problems
- Fit the model/algorithm and use it to make predictions on our data
- Evaluating a model
- Improve a model
- Save and load a trained model
- Putting it all together! 

### An end-to-end Scikit-Learn workflow

In [2]:
# Getting the data
import pandas as pd
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
# Create feature matrix (X)
X = heart_disease.drop("target", axis=1)

# Create label Matrix (Y)
y = heart_disease.target

In [5]:
# Choose the right estimator/algorithm for our problems
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# we will keep default parameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [6]:
# Fit the model/algorithm and use it 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [11]:
clf.fit(X_train, y_train);

In [12]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
284   61    1   0       140   207    0        0      138      1      1.9   
222   65    1   3       138   282    1        0      174      0      1.4   
265   66    1   0       112   212    0        0      132      1      0.1   
292   58    0   0       170   225    1        0      146      1      2.8   
239   35    1   0       126   282    0        0      156      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
179   57    1   0       150   276    0        0      112      1      0.6   
118   46    0   1       105   204    0        1      172      0      0.0   
87    46    1   1       101   197    1        1      156      0      0.0   
198   62    1   0       120   267    0        1       99      1      1.8   
229   64    1   2       125   309    0        1      131      1      1.8   

     slope  ca  thal  
284      2   1     3  
222      1   1     2  
265      2   1     2  
292      1   2     1  
239      2   0     3  
..     ...  ..   ...  
179      1   1     1  
118      2   0     2  
87       2   0     3  
198      1   2     3  
229      1   0     3  

[242 rows x 13 columns]

In [13]:
#  make predictions on our data
import numpy as np
y_preds = clf.predict(X_test)

In [17]:
y_preds

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [23]:
np.array(y_test)

array([0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1], dtype=int64)

In [19]:
# Evaluating a model on training and test data
clf.score(X_train, y_train)

1.0

In [20]:
clf.score(X_test, y_test)

0.8360655737704918

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.77      0.89      0.83        27
           1       0.90      0.79      0.84        34

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61



In [24]:
confusion_matrix(y_test, y_preds)

array([[24,  3],
       [ 7, 27]], dtype=int64)

In [25]:
accuracy_score(y_test, y_preds)

0.8360655737704918

In [27]:
# Evaluating a model
# Try different amount of n_estimators
np.random.seed(42)
for i in range(10,100,10) :
    print(f"Trying model with {i} estimators")
    clf= RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set : {clf.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 10 estimators
Model accuracy on test set : 81.97%

Trying model with 20 estimators
Model accuracy on test set : 81.97%

Trying model with 30 estimators
Model accuracy on test set : 83.61%

Trying model with 40 estimators
Model accuracy on test set : 80.33%

Trying model with 50 estimators
Model accuracy on test set : 85.25%

Trying model with 60 estimators
Model accuracy on test set : 81.97%

Trying model with 70 estimators
Model accuracy on test set : 83.61%

Trying model with 80 estimators
Model accuracy on test set : 81.97%

Trying model with 90 estimators
Model accuracy on test set : 85.25%



In [28]:
# Save and load a trained model
import pickle

pickle.dump(clf, open("random_forest_model_1.pkl", "wb"))

In [29]:
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.score(X_test, y_test)

0.8524590163934426