In [1]:
import numpy as np

## Datatypes and Attributes 

#### Numpy's main data type is nd arrays

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2,3],[4,5,6]])

a3 = np.array([ [[1,2,3],[4,5,6],[7,8,9]] , [[10,11,12],[13,14,15],[16,17,18]] ])

In [6]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
a1.dtype

dtype('int32')

#### Creating data frame from numpy array 

In [15]:
import pandas as pd

In [16]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

#### creating arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
ones = np.ones((2,3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[6, 8, 3, 0, 4],
       [4, 8, 7, 2, 8],
       [0, 3, 3, 2, 0]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
np.random.random((3,5))

array([[0.63817382, 0.73930844, 0.83821238, 0.75401862, 0.58679056],
       [0.27469383, 0.9229305 , 0.03373908, 0.86355984, 0.73887109],
       [0.49715219, 0.44989732, 0.37190374, 0.04175084, 0.15173451]])

In [28]:
np.random.rand(3,5)

array([[0.52936486, 0.21704736, 0.89197927, 0.69758663, 0.37635747],
       [0.39357058, 0.45406862, 0.65260069, 0.5963924 , 0.51388023],
       [0.23797408, 0.5810544 , 0.0267163 , 0.08864081, 0.85019672]])

#### np.random.seed() or pseudo random numbers

In [31]:
# With the seed reset (every time), the same set of numbers will appear every time.
# If the random seed is not reset, different numbers appear with every invocation:

np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [32]:
# above code will generate same array after every run

#(pseudo-)random numbers work by starting with a number (the seed), multiplying it by a large number, adding an offset, 
#then taking modulo of that sum. The resulting number is then used as the seed to generate the next "random" number. 
#When you set the seed (every time), it does the same thing every time, giving you the same numbers.